// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB7ff3Xjs15RZK4s8BTJE9uSnuucJGoY8',
    appId: '1:996601575302:web:e4727be6778bef9d409e07',
    messagingSenderId: '996601575302',
    projectId: 'expense-tracker-cb974',
    authDomain: 'expense-tracker-cb974.firebaseapp.com',
    storageBucket: 'expense-tracker-cb974.firebasestorage.app',
    measurementId: 'G-N3536TPMJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4NofM8E-1AJhcBxOympoJajEgyVhxVN4',
    appId: '1:996601575302:android:4737c215e1773166409e07',
    messagingSenderId: '996601575302',
    projectId: 'expense-tracker-cb974',
    storageBucket: 'expense-tracker-cb974.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArueAsSkEET7duge7W7z2GVIIzNEgH8eU',
    appId: '1:996601575302:ios:3a59c8eb80d0da6a409e07',
    messagingSenderId: '996601575302',
    projectId: 'expense-tracker-cb974',
    storageBucket: 'expense-tracker-cb974.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArueAsSkEET7duge7W7z2GVIIzNEgH8eU',
    appId: '1:996601575302:ios:3a59c8eb80d0da6a409e07',
    messagingSenderId: '996601575302',
    projectId: 'expense-tracker-cb974',
    storageBucket: 'expense-tracker-cb974.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB7ff3Xjs15RZK4s8BTJE9uSnuucJGoY8',
    appId: '1:996601575302:web:60f8c39c69d50bac409e07',
    messagingSenderId: '996601575302',
    projectId: 'expense-tracker-cb974',
    authDomain: 'expense-tracker-cb974.firebaseapp.com',
    storageBucket: 'expense-tracker-cb974.firebasestorage.app',
    measurementId: 'G-NQ33Y0X6GG',
  );
}
